kind: pipeline
name: default
type: docker

steps:
  - name: build
    image: archlinux:base-devel
    volumes:
      - name: artifacts
        path: /artifacts
    environment:
      PEGASUS_PASSWORD:
        from_secret: PEGASUS_PASSWORD
    commands:
      - pacman -Syu --noconfirm
      - pacman -S --noconfirm git jdk-openjdk gradle
      - ./scripts/ci.sh $PEGASUS_PASSWORD
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USER
      key:
        from_secret: SSH_KEY
      port: 22
      command_timeout: 2m
      script:
        - cp artifacts/paper.jar cloud/local/templates/Global/Global-Server/
        - cp artifacts/paper.jar cloud/local/services/Bauserver-1/
        - cp artifacts/paper.jar cloud/local/versioncache/purpur-1.20.1/paper.jar
        - cp artifacts/paper.jar cloud/local/versioncache/purpur-1.20.1/versions/1.20.1/purpur-1.20.1.jar
    when:
      event:
        - promote
      target:
        - production
  - name: notify
    image: curlimages/curl
    environment:
      webhook:
        from_secret: WEBHOOK
      message: ""
    commands:
      - MESSAGE="Deployment ${DRONE_BUILD_STATUS} on ${DRONE_REPO}/${DRONE_REPO_BRANCH}"
      - |
        curl -X POST -H "Content-type: application/json" --data "{\"content\": \":rocket: $MESSAGE\"}" $webhook
    when:
      status: [ success, failure, changed ]
      event: [ promote ]

volumes:
  - name: artifacts
    host:
      path: /home/user/artifacts